Map<String, String> techStackImages = {
  'Flutter': 'assets/icons/flutter.svg',
  'Firebase': 'assets/icons/firebase.svg',
  'MongoDB': 'assets/icons/mongo.svg',
  'NodeJS': 'assets/icons/node.svg',
  'Python': 'assets/icons/python.svg',
  'Docker': 'assets/icons/docker.svg',
  'Typescript': 'assets/icons/ts.svg',
  'Linux': 'assets/icons/linux.png',
  'Git': 'assets/icons/git.png',
  'Go': 'assets/icons/go.png',
  'Kubernetes': 'assets/icons/k8.svg',
  'AWS': 'assets/icons/aws.svg',
  'Tensorflow': 'assets/icons/tf.svg',
};
